// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA8_vQ7HLWY4XRwf139S4owuJwmqVf1pY',
    appId: '1:115691060601:web:958445769280c91e0983a8',
    messagingSenderId: '115691060601',
    projectId: 'fir-mini-project-2b367',
    authDomain: 'fir-mini-project-2b367.firebaseapp.com',
    storageBucket: 'fir-mini-project-2b367.firebasestorage.app',
    measurementId: 'G-Y1196Q5MTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2wc3nG4daS2EwT7Ov9bB_6Au2jfyKpk',
    appId: '1:115691060601:android:f3e4dc777bd949b40983a8',
    messagingSenderId: '115691060601',
    projectId: 'fir-mini-project-2b367',
    storageBucket: 'fir-mini-project-2b367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIfz8koYlXcWmVhEh87Y9GMijCkDML1l0',
    appId: '1:115691060601:ios:0d6739f8e4233e870983a8',
    messagingSenderId: '115691060601',
    projectId: 'fir-mini-project-2b367',
    storageBucket: 'fir-mini-project-2b367.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

}